version: '2'
linters:
  default: all
  disable:
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl_v5
    # retired
    - exhaustruct
    - gomodguard
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - dupl
          - goconst
        path: _test\.go$
  settings:
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - 'github.com/nalgeon/be'
            - 'github.com/Defacto2/helper'
            - 'github.com/Defacto2/magicnumber'
            - 'github.com/Defacto2/archive'
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
